baseURL = "https://phalt.github.io/"
languageCode = "en-gb"
title = "Paul writes software"
theme = "cupper-hugo-theme"
googleAnalytics = "UA-53299289-2"

[imaging]
  quality = 99

[permalinks]
  post = "/:filename/"

[params]
    portrait = "img/portrait.jpg"
    author = "Paul Hallett"
    description = "Infinitely Protean Machine"
    footer = "All content copyright Paul Hallett 2019"

[menu]
  [[menu.nav]]
    name = "Home"
    url = "/"
    weight = 1

  [[menu.nav]]
    name = "Blog"
    url = "/post/"
    weight = 2

  [[menu.nav]]
    name = "Projects"
    url = "/projects/"
    weight = 3

  [[menu.nav]]
    name = "RSS"
    url = "/index.xml"
    weight = 5

  [[menu.foo]]
    name = "PokéAPI - The Pokémon API"
    url = "https://pokeapi.co"
    weight = 3

  [[menu.foo]]
    name = "Django API Styleguide"
    url = "https://github.com/phalt/django-api-domains"
    weight = 4
